name: Validate Commit and PR Format

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Title Format
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        if [[ ! "${{ github.event.pull_request.title }}" =~ ^[a-zA-Z]+-[0-9]+:\ .+ ]]; then
          echo "::error::PR title must follow format: [prefix]-[number]: {message}"
          echo "Valid examples: 'abc-123: Fix login bug' or 'DEV-456: Update config'"
          echo "Observed title: '${{ github.event.pull_request.title }}'"
          exit 1
        fi

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Commit Messages
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          RANGE="${{ github.event.before }}..${{ github.event.after }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        fi

        git log --pretty=format:%s $RANGE | while read -r msg; do
          if [[ ! "$msg" =~ ^[a-zA-Z]+-[0-9]+:\ .+ ]]; then
            echo "::error::Commit message must follow format: [prefix]-[number]: {message}"
            echo "Offending commit: '$msg'"
            echo "Valid example: 'fix-789: Resolve null pointer exception'"
            exit 1
          fi
        done
